import { Injectable } from '@angular/core';
import { Review } from '../model/review.model';

@Injectable({
  providedIn: 'root',
})
export class ReviewsService {
  reviews: Review[] = [
    {
      id: 1,
      reviewerName: 'Ana',
      comment: 'Usluga je bila izvrsna, sve preporuke!',
      rating: 5,
    },
    {
      id: 2,
      reviewerName: 'Ivan',
      comment: 'Brza usluga, ljubazno osoblje.',
      rating: 4,
    },
    {
      id: 3,
      reviewerName: 'Marija',
      comment: 'Nisam bio zadovoljan kvalitetom usluge.',
      rating: 2,
    },
    {
      id: 4,
      reviewerName: 'Petar',
      comment: 'Sve je bilo u redu, ali malo preskupo.',
      rating: 3,
    },
    {
      id: 5,
      reviewerName: 'Luka',
      comment: 'Vrlo profesionalno, definitivno ću ponovno koristiti.',
      rating: 5,
    },
    {
      id: 6,
      reviewerName: 'Ema',
      comment: 'Usluga je mogla biti bolja, komunikacija je bila slaba.',
      rating: 3,
    },
    {
      id: 7,
      reviewerName: 'Sara',
      comment: 'Sjajna usluga, sve je bilo kako smo dogovorili.',
      rating: 4,
    },
    {
      id: 8,
      reviewerName: 'Marko',
      comment: 'Prezadovoljan sam uslugom, sve pohvale!',
      rating: 5,
    },
    {
      id: 9,
      reviewerName: 'Tina',
      comment: 'Usluga je bila brza i efikasna, ali nedostajalo je detalja.',
      rating: 3,
    },
    {
      id: 10,
      reviewerName: 'Goran',
      comment: 'Odlična usluga, sve je bilo točno na vrijeme.',
      rating: 5,
    },
    {
      id: 11,
      reviewerName: 'Ivana',
      comment: 'Malo je bilo kašnjenja, ali sve u svemu korektno.',
      rating: 3,
    },
    {
      id: 12,
      reviewerName: 'Tomislav',
      comment: 'Nisam zadovoljan komunikacijom, teško ih je bilo dobiti.',
      rating: 2,
    },
    {
      id: 13,
      reviewerName: 'Matej',
      comment: 'Vrlo ljubazni, sve odrađeno prema dogovoru.',
      rating: 4,
    },
    {
      id: 14,
      reviewerName: 'Jelena',
      comment: 'Skupi su, ali kvaliteta opravdava cijenu.',
      rating: 5,
    },
    {
      id: 15,
      reviewerName: 'Davor',
      comment: 'Sve je bilo u redu, ali moglo je biti brže.',
      rating: 3,
    },
    {
      id: 16,
      reviewerName: 'Karla',
      comment: 'Usluga je bila iznad očekivanja, svaka čast!',
      rating: 5,
    },
    {
      id: 17,
      reviewerName: 'Bruno',
      comment: 'Kvaliteta usluge je bila osrednja, očekivao sam više.',
      rating: 3,
    },
    {
      id: 18,
      reviewerName: 'Nina',
      comment: 'Vrlo profesionalno, preporučujem svakome.',
      rating: 5,
    },
    {
      id: 19,
      reviewerName: 'Filip',
      comment: 'Usprkos kašnjenju, usluga je bila korektna.',
      rating: 3,
    },
    {
      id: 20,
      reviewerName: 'Marin',
      comment: 'Sjajna usluga, sve pohvale za ekipu!',
      rating: 5,
    },
    {
      id: 21,
      reviewerName: 'Helena',
      comment: 'Nisam zadovoljna, usluga nije ispunila očekivanja.',
      rating: 2,
    },
    {
      id: 22,
      reviewerName: 'Maja',
      comment: 'Odlična komunikacija i usluga, preporučujem!',
      rating: 5,
    },
    {
      id: 23,
      reviewerName: 'Stjepan',
      comment: 'Bili su ljubazni, ali usluga je kasnila.',
      rating: 3,
    },
    {
      id: 24,
      reviewerName: 'Nikolina',
      comment: 'Vrlo efikasno i profesionalno, hvala!',
      rating: 5,
    },
    {
      id: 25,
      reviewerName: 'Andrija',
      comment: 'Očekivao sam više, ali sveukupno solidno.',
      rating: 3,
    },
    {
      id: 26,
      reviewerName: 'Anja',
      comment: 'Usluga je bila izvrsna, svi dogovori su ispoštovani.',
      rating: 5,
    },
    {
      id: 27,
      reviewerName: 'Darko',
      comment: 'Cijena je visoka za uslugu koju nude.',
      rating: 3,
    },
    {
      id: 28,
      reviewerName: 'Lea',
      comment: 'Preporučujem! Sve je bilo odrađeno brzo i točno.',
      rating: 5,
    },
    {
      id: 29,
      reviewerName: 'Boris',
      comment: 'Nisam zadovoljan, očekivao sam više.',
      rating: 2,
    },
    {
      id: 30,
      reviewerName: 'Martina',
      comment: 'Odlično iskustvo, sve je bilo po dogovoru.',
      rating: 5,
    },
    {
      id: 31,
      reviewerName: 'Ante',
      comment: 'Brzo i efikasno, ali malo preskupo.',
      rating: 4,
    },
    {
      id: 32,
      reviewerName: 'Iva',
      comment: 'Sve pohvale, vrhunska usluga.',
      rating: 5,
    },
    {
      id: 33,
      reviewerName: 'Josip',
      comment: 'Dobra usluga, ali skupa.',
      rating: 3,
    },
    {
      id: 34,
      reviewerName: 'Toni',
      comment: 'Usluga je bila ok, ali bilo je prostora za poboljšanje.',
      rating: 3,
    },
    {
      id: 35,
      reviewerName: 'Sanja',
      comment: 'Vrlo ljubazni i profesionalni.',
      rating: 4,
    },
    {
      id: 36,
      reviewerName: 'Damir',
      comment: 'Sve je bilo odrađeno prema dogovoru, bez greške.',
      rating: 5,
    },
    {
      id: 37,
      reviewerName: 'Zrinka',
      comment: 'Komunikacija je mogla biti bolja, ali usluga je bila dobra.',
      rating: 3,
    },
    {
      id: 38,
      reviewerName: 'Kristijan',
      comment: 'Kvaliteta usluge je odlična, preporučujem.',
      rating: 5,
    },
    {
      id: 39,
      reviewerName: 'Mirna',
      comment: 'Sve je bilo u redu, ali malo preskupo za ono što nude.',
      rating: 3,
    },
    {
      id: 40,
      reviewerName: 'Nenad',
      comment: 'Odlična usluga, sve preporuke!',
      rating: 5,
    },
    {
      id: 41,
      reviewerName: 'Valentina',
      comment: 'Vrlo profesionalni, sve je bilo odrađeno bez problema.',
      rating: 4,
    },
    {
      id: 42,
      reviewerName: 'Roko',
      comment: 'Usluga je bila u redu, ali komunikacija je mogla biti bolja.',
      rating: 3,
    },
    {
      id: 43,
      reviewerName: 'Tea',
      comment: 'Nisam zadovoljna, bilo je puno kašnjenja.',
      rating: 2,
    },
    {
      id: 44,
      reviewerName: 'Hrvoje',
      comment: 'Odlična usluga, sve je bilo točno prema dogovoru.',
      rating: 5,
    },
    {
      id: 45,
      reviewerName: 'Tereza',
      comment: 'Brzo i učinkovito, preporučujem svakome.',
      rating: 5,
    },
    {
      id: 46,
      reviewerName: 'Željko',
      comment: 'Usluga je bila dobra, ali ne savršena.',
      rating: 4,
    },
    {
      id: 47,
      reviewerName: 'Diana',
      comment: 'Bilo je manjih problema, ali sve u svemu ok.',
      rating: 3,
    },
    {
      id: 48,
      reviewerName: 'Dino',
      comment: 'Usluga je bila korektna, ali očekivao sam više.',
      rating: 3,
    },
    {
      id: 49,
      reviewerName: 'Vanja',
      comment: 'Nisam bio zadovoljan, puno kašnjenja i nesporazuma.',
      rating: 2,
    },
    {
      id: 50,
      reviewerName: 'Miroslav',
      comment: 'Sve je bilo savršeno, usluga na visokom nivou.',
      rating: 5,
    },
    {
      id: 51,
      reviewerName: 'Ela',
      comment: 'Usluga je bila u redu, ali ne vrijedi cijene.',
      rating: 3,
    },
    {
      id: 52,
      reviewerName: 'Mislav',
      comment: 'Sjajno iskustvo, sve pohvale!',
      rating: 5,
    },
    {
      id: 53,
      reviewerName: 'Sandra',
      comment: 'Nisam zadovoljna, očekivala sam više od ovakve usluge.',
      rating: 2,
    },
    {
      id: 54,
      reviewerName: 'Zoran',
      comment: 'Sve je bilo ok, ali ništa posebno.',
      rating: 3,
    },
    {
      id: 55,
      reviewerName: 'Kristina',
      comment: 'Vrlo profesionalno, sve je bilo odrađeno bez greške.',
      rating: 5,
    },
    {
      id: 56,
      reviewerName: 'Lovro',
      comment: 'Usluga je bila dobra, ali skupa.',
      rating: 3,
    },
    {
      id: 57,
      reviewerName: 'Lana',
      comment: 'Sve je bilo odlično, definitivno preporučujem!',
      rating: 5,
    },
    {
      id: 58,
      reviewerName: 'Gordana',
      comment: 'Nisam zadovoljna, usluga nije bila na očekivanom nivou.',
      rating: 2,
    },
    {
      id: 59,
      reviewerName: 'Vedran',
      comment: 'Sve je bilo odrađeno prema dogovoru, nemam primjedbi.',
      rating: 4,
    },
    {
      id: 60,
      reviewerName: 'Martina',
      comment: 'Brzo i efikasno, sve pohvale!',
      rating: 5,
    },
    {
      id: 61,
      reviewerName: 'Ivica',
      comment: 'Malo preskupo, ali kvalitetno.',
      rating: 4,
    },
    {
      id: 62,
      reviewerName: 'Mirko',
      comment: 'Vrlo ljubazni i profesionalni, sve je odrađeno točno.',
      rating: 5,
    },
    {
      id: 63,
      reviewerName: 'Renata',
      comment: 'Nisam zadovoljna, bilo je previše nesporazuma.',
      rating: 2,
    },
    {
      id: 64,
      reviewerName: 'Stipe',
      comment: 'Dobra usluga, ali nije opravdala cijenu.',
      rating: 3,
    },
  ];

  getRandomReviews(): Review[] {
    return this.reviews.sort(() => 0.5 - Math.random()).slice(0, 5);
  }
}
