export const serviceCategories = [
  {name: 'Građevinarstvo', value: 'GRAĐEVINARSTVO'},
  {name: 'Instrukcije', value: 'INSTRUKCIJE'},
  {name: 'Čišćenje Doma', value: 'ČIŠĆENJE_DOMA'},
  {name: 'Vodoinstalaterske Usluge', value: 'VODOINSTALATERSKE_USLUGE'},
  {name: 'Elektro Usluge', value: 'ELEKTRO_USLUGE'},
  {name: 'Uređenje Vrtova', value: 'UREĐENJE_VRTOVA'},
  {name: 'Frizerske Usluge', value: 'FRIZERSKE_USLUGE'},
  {name: 'Podučavanje', value: 'PODUČAVANJE'},
  {name: 'Čuvanje Djece', value: 'ČUVANJE_DJECE'},
  {name: 'Grafički Dizajn', value: 'GRAFIČKI_DIZAJN'},
  {name: 'Fotografija', value: 'FOTOGRAFIJA'},
  {name: 'Razvoj Web Stranica', value: 'RAZVOJ_WEB_STRANICA'},
  {name: 'Ugostiteljske Usluge', value: 'UGOSTITELJSKE_USLUGE'},
  {name: 'Planiranje Događaja', value: 'PLANIRANJE_DOGAĐAJA'},
  {name: 'Čuvanje Ljubimaca', value: 'ČUVANJE_LJUBIMACA'},
  {name: 'Stolarija', value: 'STOLARIJA'},
  {name: 'Popravak Automobila', value: 'POPRAVAK_AUTOMOBILA'},
  {name: 'Fitness Trening', value: 'FITNESS_TRENING'},
  {name: 'Glazbene Lekcije', value: 'GLAZBENE_LEKCIJE'},
  {name: 'Pravne Usluge', value: 'PRAVNE_USLUGE'},
  {name: 'Računovodstvo', value: 'RAČUNOVODSTVO'},
  {name: 'Dizajn Interijera', value: 'DIZAJN_INTERIJERA'},
  {name: 'Prevoditeljske Usluge', value: 'PREVODITELJSKE_USLUGE'},
  {name: 'Marketing Konsultacije', value: 'MARKETING_KONSULTACIJE'}
]
